broweb/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('broweb.views',
    url(r'^login-or-create/$', 'login_or_create', name="login"),
    url(r'^logout/$', 'logout', name="logout"),
    url(r'^books/(?P<book_id>\d+)/downvote/$', 'downvote', name="downvote"),
    url(r'^books/(?P<book_id>\d+)/upvote/$', 'upvote', name='upvote'),
    url(r'^$', 'index', name="index"),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'', include('broweb.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

broweb/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
    def get_upload_to(self,filename):
        return 'books/images/%s/%s' % (self.id,filename)
        
    author = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    pages = models.IntegerField()
    img = models.ImageField(upload_to=get_upload_to, null=True, blank=True)
    mode = models.CharField(max_length=16,
        choices=(
            ('reading','Reading'),('read','Read'),('reject','Rejected'),('upcoming','Upcoming'),('proposed','Proposed'),
            ),
        default='proposed'
        )
    
    def current_reading(self):
        return self.readings.order_by('-start_date')[0]
        
    def comments(self):
        return self.current_readings().comments
        
    def __str__(self):
        return '%s by %s' % (self.name,self.author)

    
class Link(models.Model):
    book = models.ForeignKey(Book, related_name='links')
    link = models.URLField(max_length=500)
    name = models.CharField(max_length=64,choices=(('amazon','Amazon.com'),('blank','(blank)')),default="blank")
    
class Reading(models.Model):
    book = models.ForeignKey(Book, related_name='readings')
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    
    def __str__(self):
        return ('Reading %s from %s until %s' % (self.book,self.start_date,self.end_date))
    
    def time_left(self):
        return (self.end_date - datetime.datetime.now())

    def pages_per_day(self):
        return self.book.pages / (self.end_date - self.start_date).days
        
    def day_num(self):
        return (datetime.datetime.now()-self.start_date).days
        
    def through_pages(self):
        return self.day_num() * self.pages_per_day()
        
    def left_pages(self):
        return self.book.pages - self.through_pages ()


class Comment(models.Model):
    book = models.ForeignKey(Book, related_name="comments")
    text = models.TextField()
    ts = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True,auto_now_add=True)
    user = models.ForeignKey(User, related_name="comments")
    
class Vote(models.Model):
    book = models.ForeignKey(Book, related_name='votes')
    vote = models.IntegerField()
    user = models.ForeignKey(User,null=True)
    ts = models.DateTimeField()

broweb/forms.py
from django import forms
import models

class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        exclude = ('mode',)
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        includes = ('book','text')

broweb/views.py
import datetime
import json
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Sum, Count
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as dlogout
from django.contrib import messages

from forms import BookForm, CommentForm
from models import Book, Vote

def index(request):
    
    now = datetime.datetime.now()
    current_books = Book.objects.filter(mode='reading',readings__end_date__gt=now).select_related('readings')
    proposed = Book.objects.filter(mode='proposed')\
        .annotate(sum_votes=Sum('votes__vote'),count_votes=Count('votes'))\
        .order_by('-sum_votes')
    context = {
        'current_books':current_books,
        'proposed':proposed,
    }
    
    if request.method == 'POST':
        book_form = BookForm(request.POST)
        if book_form.is_valid():
            book_form.save()
            messages.success(request,"You successfully proposed a book!")
            return redirect(index)
    else:
        book_form = BookForm()
    context['book_form'] = book_form

    return render_to_response('broweb/index.html',RequestContext(request,context))


def submit_comment(request):
    if not request.POST:
        return HttpResponse(status=405)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        pass


def login_or_create(request):
    username = request.REQUEST.get('username')
    password = request.REQUEST.get('password')
    user = authenticate(username=username, password=password)
    if user is None:
        user = User.objects.create_user(username,email='',password=password)
        user = authenticate(username=username, password=password)
        login(request,user)
        messages.warning(request,'Hi %s, we created a new account for you!' % username)
    else:
        login(request,user)
        messages.success(request,'Hi %s, you were successfully logged in.' % username)
    
    return redirect(request.META.get('HTTP_REFERER'),'/')
   
def logout(request):
    dlogout(request)
    messages.success(request,'You\'ve been logged out.')
    return redirect(request.META.get('HTTP_REFERER'),'/')
    
def ok_to_vote(request,book_id):
    if not request.session.get('votes'):
        request.session['votes'] = {}
    voted = request.session['votes'].get(int(book_id))
    if voted is not None and datetime.datetime.now() <= voted + datetime.timedelta(hours=1):
        return False
    else:
        request.session['votes'][int(book_id)] = datetime.datetime.now()
        request.session.modified = True
        return True

def downvote(request,book_id):
    if not request.user.is_authenticated():
        return HttpResponse(json.dumps({'message':"You need to login to vote. It's easy, just type in any username or password you want!"}),status=403)
    book = get_object_or_404(Book,id=book_id)
    if not ok_to_vote(request,book_id):
        return HttpResponse(json.dumps({'message':'You can only vote once an hour.'}),status=403)
    now = datetime.datetime.now()
    vote = Vote(book=book,ts=now,vote=-1, user=request.user).save()
    return HttpResponse(status=200)
    
def upvote(request,book_id):
    if not request.user.is_authenticated():
        return HttpResponse(json.dumps({'message':"You need to login to vote. It's easy, just type in any username or password you want!"}),status=403)
    book = get_object_or_404(Book,id=book_id)
    if not ok_to_vote(request,book_id):
        return HttpResponse(json.dumps({'message':'You can only vote once an hour.'}),status=403)
    now = datetime.datetime.now()
    vote = Vote(book=book,ts=now,vote=1, user=request.user).save()
    return HttpResponse(status=200)

    

templates/broweb/index.html
<html>
<head>
	<title>Bros and Books</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" />
	<style>
	#content {
		margin-top:55px;
	}
	#message-container {
		position:absolute;
		left:15%;
		right:15%;
		top:40px;
		z-index:100;
	}
	.current-book {
		margin-top:10px;
		height:75px;
		position:relative;
	}
	img.book {
		max-height:75px;
		max-width:75px;
		position:absolute;
		right:10px;
		top:10px;
	}
	#account {
		position:absolute;
		right:10px;
		top:10px;
	}
	input.vote {
		width:auto;height:auto;
	}
	</style>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
	<script type="text/javascript" src="/static/bootstrap/js/bootstrap-modal.js"></script>
	<script type="text/javascript">
	function alertMessage(data) {
		var $alert = $("#alert-message-tpl").tmpl(data)
		$alert.hide().appendTo('#message-container').show('slideDown')
		setTimeout(function() { $alert.hide('slideUp') }, 2000)
	}
	$(function() {
		$('form.upvote,form.downvote').submit(function(e) {
			var $form = $(this);
			e.preventDefault()
			$.post($form.attr('action'),$form.serialize())
				.success(function(data,status) {
					window.location.reload()
				})
				.error(function(data) {
					data = JSON.parse(data.responseText)
					data['tag'] = 'warning'
					alertMessage(data)
				})
			
		})
		$('a.close').on('click',function() {
			$(this).closest('.alert').remove()
		})
		setTimeout(function() { $('#message-container .alert').hide('slideUp') },3000)
		$('#comment-modal').modal(options)
	})
	</script>
	<script id="alert-message-tpl" type="text/template">
		<div class="alert ${ tag }">
			<a class="close" href="javascript:void(0)" onclick="$(this).closest('.alert').remove()">×</a>
			<p>${ message }</p>
		</div>
	</script>


</head>
<body>


	

	
	<div id="comment-modal" class="modal fade">
	  <div class="modal-header">
	    <a class="close" data-dismiss="modal">×</a>
	    <h3>Comment on book...</h3>
	  </div>
	  <div class="modal-body">
	    <p>//TODO: Implement commenting on books!</p>
	  </div>
	  <div class="modal-footer">
	    <a href="#" class="btn btn-primary">Save changes</a>
	    <a href="#" onclick="$('#comment-modal').modal('hide')" class="btn">Close</a>
	  </div>
	</div>
	
	
	<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
				
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
				</a>
				
        <a class="brand" href="./">Bros and Books</a>
				
        <div class="nav-collapse">
						{% if request.user.is_authenticated %}
	          <ul class="nav">
		          <li>
								<a href="{% url logout %}">Logout</a>
							</li>
						</ul>
						{% else %}
	          <ul class="nav pull-right">
		          <li>
								<a href="javascript:void(0)" onclick="$('form#login').submit()">Login/Create</a>
							</li>
						</ul>
						
						<form id="login" class="navbar-search pull-right" action="{% url login %}" method="post">{% csrf_token %}
	          		<input class="search-query span2" type="text" name="username" placeholder="Username" />
	          		<input class="search-query span2" type="password" name="password" placeholder="Password" />
						</form>

						

						{% endif %}
        </div><!--/.nav-collapse -->
				
      </div>
    </div>
  </div>
	
	<div id="content" class="container">
		
		<div id="message-container">
			{% if messages %}
				{% for message in messages %}
				<div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
					<a class="close" href="#">×</a>
					<p>{{ message }}</p>
				</div>
				{% endfor %}
			{% endif %}
		</div>
		
		<div id="current">

			<table>
			{% for book in current_books %}
				<div class="current-book alert alert-info">
					<p>You're currently supposed to be reading {% if book.links.all.0 %}<a href="{{ book.links.all.0 }}">"{{book.name}}"</a>{% else %}"{{book.name}}"{% endif %} by {{book.author}}.</p>
					<p>You've got <strong>{{book.current_reading.time_left.days}} days left</strong>.<p>
					<p>You should be reading <strong>{{book.current_reading.pages_per_day}} pages per day</strong>. At that rate, you'd be on page <strong>{{book.current_reading.through_pages}}</strong>, with {{book.current_reading.left_pages}} to go.</p>
					{% if book.img %}<img class="book" src="{{book.img.url}}" />{% endif %}
				</div>
			{% empty %}
				<p>Not currently reading anything!</p>
			{% endfor %}
			</table>
		</div>
		
		<div id="proposed">
			<h2>Proposed Books</h2>
			<form method="post" action="{% url index %}">
				{% csrf_token %}
				<table class="table">
				<tr>
					<th>Name</th><th>Cover</th><th>Author</th><th># Pages</th>
				</tr>
				<tr>
					<td class="control-group {% if book_form.name.errors %}error{% endif %}">
						<span class="help-inline">{{ book_form.name.errors }}</span>
						{{ book_form.name }}
					</td>
					<td class="control-group {% if book_form.img.errors %}error{% endif %}">
						<span class="help-inline">{{ book_form.img.errors }}</span>
						{{ book_form.img }}
					</td>
					<td class="control-group {% if book_form.author.errors %}error{% endif %}">
						<span class="help-inline">{{ book_form.author.errors }}</span>
						<input id="id_author" class="input-medium" name="author">
					</td>
					<td class="control-group {% if book_form.pages.errors %}error{% endif %}">
						<span class="help-inline">{{ book_form.pages.errors }}</span>
						<input id="id_pages" class="input-small" name="pages">
					</td>
				</tr>
				<tr>
					<td></td><td></td><td></td><td><input class="btn btn-primary" type="submit" value="Propose!"></td>
				</tr>
				<table>
			</form>
			<table class="table table-striped">
			{% for book in proposed %}
				<tr class="book">
						<td>{{book.name}}</td>
						<td>{% if book.img %}<img class="book" src="{{book.img.url}}" />{% endif %}</td>
						<td>{{book.author}}</td>
						<td>
							<form class="upvote" action="{% url upvote book.id %}" method="post">
								{% csrf_token %}
								<button class="btn btn-success" type="submit">
									<i class="icon-arrow-up"></i>
								</button>
								
							</form>
						</td>
						<td>
							<form class="downvote" action="{% url downvote book.id %}" method="post">
								{% csrf_token %}
								<button class="btn btn-danger" type="submit">
									<i class="icon-arrow-down"></i>
								</button>
								
							</form>
						</td>
						<td><h3>{{book.sum_votes}}</h3> <h6>From {{book.count_votes}} votes</h6></td>
						<td><a class="btn small" data-toggle="modal" href="#comment-modal" >Comment</a></td>
				</tr>
			{% empty %}
				<tr>
						<td>Sorry. No proposed books.</td><td></td><td></td><td></td><td></td>
				</tr>
			{% endfor %}
			</table>
		</div>
		
	</div>
</body>
</html>